# Generated by Selenium IDE
from selenium import webdriver
from selenium.webdriver.common.by import By


class TestLogin():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_login(self):
    self.open_home_page()
    # self.driver.set_window_size(1920, 1080)
    self.login()

  def login(self):
    self.driver.find_element(By.ID, "form_user_loginhtml_input_0_login").click()
    self.driver.find_element(By.ID, "form_user_loginhtml_input_0_login").send_keys("Директор1")
    self.driver.find_element(By.ID, "form_user_loginhtml_password_0_password").click()
    self.driver.find_element(By.ID, "form_user_loginhtml_password_0_password").send_keys("123456")
    self.driver.find_element(By.ID, "form_user_loginhtml_button_1_button").click()

  def open_home_page(self):
    self.driver.get("https://stablev10.ci.dental-pro.online/")

  
