# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestLogin():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_login(self):
    self.driver.get("https://betav10.ci.dental-pro.online/user/login.html")
    self.driver.set_window_size(1552, 840)
    self.driver.find_element(By.ID, "form_user_loginhtml_input_0_login").click()
    self.driver.find_element(By.ID, "form_user_loginhtml_input_0_login").send_keys("Директор1")
    self.driver.find_element(By.ID, "form_user_loginhtml_password_0_password").click()
    self.driver.find_element(By.ID, "form_user_loginhtml_password_0_password").send_keys("123456")
    self.driver.find_element(By.ID, "form_user_loginhtml_button_1_button").click()
    self.driver.find_element(By.CSS_SELECTOR, ".userLine").click()
    self.driver.find_element(By.LINK_TEXT, "Выход").click()
    self.driver.execute_script("window.scrollTo(0,0)")
  
